In [ ]:
from pathlib import Path
import sys
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [2]:
from config.paths import PROCESSED_DATA_DIR, INTERIM_DATA_DIR

### Load Dataset

In [4]:
df = pd.read_csv(Path(INTERIM_DATA_DIR / "pl_2025_26_nominees_stats.csv"))
df.head()

,playerId,bigChancesMissed,totalShots,goalConversionPercentage,interceptions,clearances,errorLeadToGoal,outfielderBlocks,bigChancesCreated,accuratePasses,...,expectedGoals,successfulDribbles,tackles,assists,accuratePassesPercentage,sofascoreRating,name,teamName,potm_wins,position
0,288205,8,85,10.59,20,42,0,5,33,1639,...,10.83,15,54,21,82.20,7.61,Bruno Fernandes,Manchester United,1,Midfielder
1,581310,0,0,0.00,1,37,1,0,0,707,...,NaN,1,1,0,64.80,6.90,David Raya,Arsenal,0,Goalkeeper
2,839956,30,126,21.43,5,42,0,1,9,252,...,25.43,17,15,8,65.63,7.31,Erling Haaland,Manchester City,1,Attacker
3,856714,3,40,10.00,37,78,1,12,17,1865,...,3.17,14,70,5,87.31,7.46,Declan Rice,Arsenal,0,Midfielder
4,865912,10,83,18.07,13,32,1,3,5,980,...,10.84,30,20,4,81.13,6.92,Morgan Gibbs-White,Nottingham Forest,1,Midfielder

In [5]:
additional_metrics_df = pd.read_csv(Path(INTERIM_DATA_DIR / "PFA_nominees_additional_metrics.csv"))
additional_metrics_df.head()

,player id,name,matches Played,matches started,minutes played,non penalty goals,expected assists,team position,team points,team goals scored,...,saves made outside box,saves made inside box,squad minutes share %,team goal diff per90,team on off impact per90,tackles won,touches,touches in opp box,shots blocked,ball recoveries
0,288205,Bruno Fernandes,35,35,3066,5,12.32,3,71,69,...,NaN,NaN,89.6,0.59,0.84,35,2648,91,30,167
1,856714,Declan Rice,36,35,3099,4,6.96,1,85,71,...,NaN,NaN,90.5,1.08,-0.86,33,2760,55,13,180
2,865912,Morgan Gibbs-White,37,35,3097,14,2.92,16,44,48,...,NaN,NaN,90.6,-0.09,-0.09,16,1738,127,24,110
3,839956,Erling Haaland,35,34,2958,24,2.81,2,78,77,...,NaN,NaN,86.3,1.13,0.16,7,779,213,24,41
4,934354,Antoine Semenyo,37,37,3200,16,3.12,2,78,77,...,NaN,NaN,93.4,0.20,-0.69,31,1701,176,14,143

In [6]:
additional_metrics_df.columns = additional_metrics_df.columns.str.title().str.replace(" ", "")

In [7]:
additional_metrics_df.columns

Index(['PlayerId', 'Name', 'MatchesPlayed', 'MatchesStarted', 'MinutesPlayed',
       'NonPenaltyGoals', 'ExpectedAssists', 'TeamPosition', 'TeamPoints',
       'TeamGoalsScored', 'TeamGoalsConceded', 'ChancesCreated',
       'FinalThirdPassesSuccessful', 'AccurateFinalThirdPassPerc',
       'PossessionWon', 'GroundDuelsWon%', 'AerialDuelsWon%', 'Yellows',
       'Reds', 'Fouls', 'PenaltyConceded', 'ProgressiveCarries',
       'GoalsConceded', 'SavesMade', 'SavePerc', 'GoalsPrevented',
       'SavesMadeOutsideBox', 'SavesMadeInsideBox', 'SquadMinutesShare%',
       'TeamGoalDiffPer90', 'TeamOnOffImpactPer90', 'TacklesWon', 'Touches',
       'TouchesInOppBox', 'ShotsBlocked', 'BallRecoveries'],
      dtype='str')

In [8]:
new_name = [col[0].lower() + col[1:] for col in additional_metrics_df.columns]
additional_metrics_df.columns = new_name

In [9]:
additional_metrics_df = additional_metrics_df.drop(columns=["name"])

In [10]:
additional_metrics_df.head()

,playerId,matchesPlayed,matchesStarted,minutesPlayed,nonPenaltyGoals,expectedAssists,teamPosition,teamPoints,teamGoalsScored,teamGoalsConceded,...,savesMadeOutsideBox,savesMadeInsideBox,squadMinutesShare%,teamGoalDiffPer90,teamOnOffImpactPer90,tacklesWon,touches,touchesInOppBox,shotsBlocked,ballRecoveries
0,288205,35,35,3066,5,12.32,3,71,69,50,...,NaN,NaN,89.6,0.59,0.84,35,2648,91,30,167
1,856714,36,35,3099,4,6.96,1,85,71,27,...,NaN,NaN,90.5,1.08,-0.86,33,2760,55,13,180
2,865912,37,35,3097,14,2.92,16,44,48,51,...,NaN,NaN,90.6,-0.09,-0.09,16,1738,127,24,110
3,839956,35,34,2958,24,2.81,2,78,77,35,...,NaN,NaN,86.3,1.13,0.16,7,779,213,24,41
4,934354,37,37,3200,16,3.12,2,78,77,35,...,NaN,NaN,93.4,0.20,-0.69,31,1701,176,14,143

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   playerId                    8 non-null      int64
 1   bigChancesMissed            8 non-null      int64
 2   totalShots                  8 non-null      int64
 3   goalConversionPercentage    8 non-null      float64
 4   interceptions               8 non-null      int64
 5   clearances                  8 non-null      int64
 6   errorLeadToGoal             8 non-null      int64
 7   outfielderBlocks            8 non-null      int64
 8   bigChancesCreated           8 non-null      int64
 9   accuratePasses              8 non-null      int64
 10  keyPasses                   8 non-null      int64
 11  saves                       1 non-null      float64
 12  cleanSheet                  1 non-null      float64
 13  penaltySave                 1 non-null      float64
 14  savedShotsFromInsideTheBox  1 non-null      float64
 15  runsOut                     1 non-null      float64
 16  goals                       8 non-null      int64
 17  expectedGoals               7 non-null      float64
 18  successfulDribbles          8 non-null      int64
 19  tackles                     8 non-null      int64
 20  assists                     8 non-null      int64
 21  accuratePassesPercentage    8 non-null      float64
 22  sofascoreRating             8 non-null      float64
 23  name                        8 non-null      str
 24  teamName                    8 non-null      str
 25  potm_wins                   8 non-null      int64
 26  position                    8 non-null      str
dtypes: float64(9), int64(15), str(3)
memory usage: 1.8 KB

In [12]:
df["position"].value_counts()

position
Midfielder    3
Attacker      3
Goalkeeper    1
Defender      1
Name: count, dtype: int64

In [13]:
len(df.columns)

27

In [14]:
len(additional_metrics_df.columns)

35

In [15]:
master_df = pd.merge(left=df, right=additional_metrics_df, how="inner", on="playerId")

In [16]:
col_list = [col for col in master_df.columns]

In [17]:
for col in col_list:
    if col.find("_x") != -1:
        print(col)

In [18]:
master_df.columns

Index(['playerId', 'bigChancesMissed', 'totalShots',
       'goalConversionPercentage', 'interceptions', 'clearances',
       'errorLeadToGoal', 'outfielderBlocks', 'bigChancesCreated',
       'accuratePasses', 'keyPasses', 'saves', 'cleanSheet', 'penaltySave',
       'savedShotsFromInsideTheBox', 'runsOut', 'goals', 'expectedGoals',
       'successfulDribbles', 'tackles', 'assists', 'accuratePassesPercentage',
       'sofascoreRating', 'name', 'teamName', 'potm_wins', 'position',
       'matchesPlayed', 'matchesStarted', 'minutesPlayed', 'nonPenaltyGoals',
       'expectedAssists', 'teamPosition', 'teamPoints', 'teamGoalsScored',
       'teamGoalsConceded', 'chancesCreated', 'finalThirdPassesSuccessful',
       'accurateFinalThirdPassPerc', 'possessionWon', 'groundDuelsWon%',
       'aerialDuelsWon%', 'yellows', 'reds', 'fouls', 'penaltyConceded',
       'progressiveCarries', 'goalsConceded', 'savesMade', 'savePerc',
       'goalsPrevented', 'savesMadeOutsideBox', 'savesMadeInsideBox',
       'squadMinutesShare%', 'teamGoalDiffPer90', 'teamOnOffImpactPer90',
       'tacklesWon', 'touches', 'touchesInOppBox', 'shotsBlocked',
       'ballRecoveries'],
      dtype='str')

In [19]:
master_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 61 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   playerId                    8 non-null      int64
 1   bigChancesMissed            8 non-null      int64
 2   totalShots                  8 non-null      int64
 3   goalConversionPercentage    8 non-null      float64
 4   interceptions               8 non-null      int64
 5   clearances                  8 non-null      int64
 6   errorLeadToGoal             8 non-null      int64
 7   outfielderBlocks            8 non-null      int64
 8   bigChancesCreated           8 non-null      int64
 9   accuratePasses              8 non-null      int64
 10  keyPasses                   8 non-null      int64
 11  saves                       1 non-null      float64
 12  cleanSheet                  1 non-null      float64
 13  penaltySave                 1 non-null      float64
 14  savedShotsFromInsideTheBox  1 non-null      float64
 15  runsOut                     1 non-null      float64
 16  goals                       8 non-null      int64
 17  expectedGoals               7 non-null      float64
 18  successfulDribbles          8 non-null      int64
 19  tackles                     8 non-null      int64
 20  assists                     8 non-null      int64
 21  accuratePassesPercentage    8 non-null      float64
 22  sofascoreRating             8 non-null      float64
 23  name                        8 non-null      str
 24  teamName                    8 non-null      str
 25  potm_wins                   8 non-null      int64
 26  position                    8 non-null      str
 27  matchesPlayed               8 non-null      int64
 28  matchesStarted              8 non-null      int64
 29  minutesPlayed               8 non-null      int64
 30  nonPenaltyGoals             8 non-null      int64
 31  expectedAssists             8 non-null      float64
 32  teamPosition                8 non-null      int64
 33  teamPoints                  8 non-null      int64
 34  teamGoalsScored             8 non-null      int64
 35  teamGoalsConceded           8 non-null      int64
 36  chancesCreated              8 non-null      int64
 37  finalThirdPassesSuccessful  8 non-null      int64
 38  accurateFinalThirdPassPerc  8 non-null      float64
 39  possessionWon               8 non-null      int64
 40  groundDuelsWon%             8 non-null      float64
 41  aerialDuelsWon%             8 non-null      float64
 42  yellows                     8 non-null      int64
 43  reds                        8 non-null      int64
 44  fouls                       8 non-null      int64
 45  penaltyConceded             8 non-null      int64
 46  progressiveCarries          8 non-null      int64
 47  goalsConceded               1 non-null      float64
 48  savesMade                   1 non-null      float64
 49  savePerc                    1 non-null      float64
 50  goalsPrevented              1 non-null      float64
 51  savesMadeOutsideBox         1 non-null      float64
 52  savesMadeInsideBox          1 non-null      float64
 53  squadMinutesShare%          8 non-null      float64
 54  teamGoalDiffPer90           8 non-null      float64
 55  teamOnOffImpactPer90        8 non-null      float64
 56  tacklesWon                  8 non-null      int64
 57  touches                     8 non-null      int64
 58  touchesInOppBox             8 non-null      int64
 59  shotsBlocked                8 non-null      int64
 60  ballRecoveries              8 non-null      int64
dtypes: float64(22), int64(36), str(3)
memory usage: 3.9 KB

### Save Final Dataset

In [ ]:
master_df.to_csv(Path(PROCESSED_DATA_DIR / "final_pl_2025_26_nominees_stats.csv"), index=True)